name: Building docker
run-name: Building docker by ${{ github.actor }}
on:
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.6.5
      - name: Packer build and push
        run: |-
          cd .github/docker
          source variables.sh
          export DOCKER_VERSION="$GITHUB_SHA-webpremium"
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          packer build docker-ubuntu22-php8.4-phalcon5.9.0.json
      - name: Send Discord notification
        uses: stegzilla/discord-notify@v2
        with:
          webhook_url: https://discord.com/api/webhooks/1026099782244118569/JVWVeWvs8usNtAUlbRGoRrXS2s6pajENmLBZbmRNG5k781yGBLmRWQoPeF6SDD_tIMZO
          title: Nueva imagen de docker para webpremium
          message: "776535672105.dkr.ecr.eu-west-3.amazonaws.com/infolot-base:${GITHUB_SHA}-webpremium"
          include_image: false